### ISSUE TITLE
Regarding Pretrained Models

### ISSUE THREAD

**Issue by sumit171993** [johnMinelli/TwoWaySynth#2]

**Comment by sumit171993** [comment]
Hi, thanks for solving the previous issue, can you also provide pretrained models? Thank you

**Comment by johnMinelli** [comment]
Sure, unfortunately at the moment I do not have access to the hard drive where I saved the models used for the evaluation, but I will upload them as soon as I have a chance.

**Comment by sumit171993** [comment]
Yeah, please provide. Otherwise, I need to do the training on KITTI, its large dataset. Thank you

**Comment by johnMinelli** [comment]
Sorry for the delay: 76d01720584b8e933e13e937c78dbcc73d70932f

**Comment by sumit171993** [comment]
Thank you
Regards,
Sumit
